version: '3.5'
services:
  rabbit-mq:
    image: rabbitmq:3.6.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - sabino_network
    environment:
      AMQT_HOST: localhost
      AMQT_PORT: 5672
      AMQT_USER: guest
      AMQT_PASSWORD: guest
  amqp-producer:
    build:
      context: ./spring-boot-cdc-amqp-producer
      dockerfile: Dockerfile
    image: sabinolab/spring-boot-cdc-amqp-producer
    container_name: amqp-producer
    ports:
      - "8080:8080"
    networks:
      - sabino_network
    depends_on:
      - rabbit-mq
  amqp-consumer:
    build:
      context: spring-boot-cdc-amqp-consumer
      dockerfile: Dockerfile
    image: sabinolab/spring-boot-cdc-amqp-consumer
    container_name: amqp-consumer
    ports:
      - "8081:8081"
    networks:
      - sabino_network
    depends_on:
      - rabbit-mq
  rest-api:
    build:
      context: ./spring-boot-cdc-rest-api
      dockerfile: Dockerfile
    image: sabinolab/spring-boot-cdc-rest-api
    container_name: webapp-rest-api
    ports:
      - "8082:8082"
    networks:
      - sabino_network
    depends_on:
      - rabbit-mq

networks:
  sabino_network:
    name: sabino_network
    driver: bridge