server:
  port: ${PORT:8080}

spring:
  rabbitmq:
    host: ${AMQT_HOST:localhost}
    port: ${AMQT_PORT:5672}
    username: ${AMQT_USER:guest}
    password: ${AMQT_PASSWORD:guest}
  cloud:
    stream:
      bindings:
        product-channel:
          destination: ${AMQT_ROUTE_DESTINATION:product-process}

logging:
  level:
    org.springframework.cloud: debug